edificeio/explorer

.gitignore
backend/deployment/conf.j2
backend/src/main/java/com/opendigitaleducation/explorer/Explorer.java
backend/src/main/java/com/opendigitaleducation/explorer/ExplorerConfig.java
backend/src/main/java/com/opendigitaleducation/explorer/folders/FolderExplorerDbSql.java
backend/src/main/java/com/opendigitaleducation/explorer/folders/ResourceExplorerDbSql.java
backend/src/main/java/com/opendigitaleducation/explorer/ingest/MessageIngesterPostgres.java
backend/src/main/java/com/opendigitaleducation/explorer/ingest/impl/HtmlAnalyserMessageTransformer.java
backend/src/main/java/com/opendigitaleducation/explorer/services/impl/ResourceServiceElastic.java
backend/src/test/java/com/opendigitaleducation/explorer/DiscreteFailureTest.java
backend/src/test/java/com/opendigitaleducation/explorer/ExplorerControllerTest.java
backend/src/test/java/com/opendigitaleducation/explorer/FakeMongoPlugin.java
backend/src/test/java/com/opendigitaleducation/explorer/FakePostgresPlugin.java
backend/src/test/java/com/opendigitaleducation/explorer/FullExplorerStackTest.java
backend/src/test/java/com/opendigitaleducation/explorer/IngestJobPGFailingTest.java
backend/src/test/java/com/opendigitaleducation/explorer/IngestJobStressTest.java
backend/src/test/java/com/opendigitaleducation/explorer/IngestJobTest.java
backend/src/test/java/com/opendigitaleducation/explorer/MongoPluginTest.java
backend/src/test/java/com/opendigitaleducation/explorer/ResourceServiceTest.java
backend/src/test/java/com/opendigitaleducation/explorer/tests/ExplorerTestHelper.java

Plusieurs problèmes de perf sont à noté:
- des outofmemory causé par des html trop gros
- des timeout postgres lié à des shared trop gros
- des erreurs 504 opensearch
Ce fix propose:
-  la suppression des partages historiques (et l'utilisation des nouveaux droits normalisés un peu plus légers)
- un fix permettant de prendre en compte le parsing html sur les sous ressources
WB2-537

[ODE] optimisation du job d'ingestion

---

frontend/config/resolve.ts
frontend/package.json
frontend/package.json.template
frontend/src/app/Explorer.tsx
frontend/src/features/Explorer/components/FoldersList/FoldersList.tsx
frontend/src/features/Explorer/components/ResourcesList/ResourcesList.tsx
frontend/src/features/TreeView/components/TreeViewContainer.tsx
frontend/src/main.tsx
frontend/src/queries/index.ts
frontend/src/services/index.ts
frontend/src/shared/components/LoadMore.tsx
frontend/src/shared/hooks/useIntersectionObserver.ts
frontend/src/store/explorerSlice.ts
frontend/src/store/folderSlice.ts
frontend/src/store/resourceSlice.ts
frontend/src/store/treeviewSlice.ts
frontend/tsconfig.json

- add react-query
- add infinite loading
- add skeleton fetching card
- fixes some issues with zustand store

feat: #WB2-650, add skeleton with infinite loading and fixes

---

frontend/config/resolve.ts
frontend/package.json
frontend/package.json.template
frontend/src/app/Explorer.tsx
frontend/src/features/Actionbar/hooks/useActionBar.tsx
frontend/src/features/Actionbar/hooks/useMoveModal.tsx
frontend/src/features/Explorer/components/FoldersList/FoldersList.tsx
frontend/src/features/Explorer/components/ResourcesList/ResourcesList.tsx
frontend/src/features/TreeView/components/TreeViewContainer.tsx
frontend/src/main.tsx
frontend/src/queries/index.ts
frontend/src/services/index.ts
frontend/src/shared/components/LoadMore.tsx
frontend/src/shared/hooks/useIntersectionObserver.ts
frontend/src/shared/utils/getAppParams.ts
frontend/src/store/explorerSlice.ts
frontend/src/store/folderSlice.ts
frontend/src/store/resourceSlice.ts
frontend/src/store/treeviewSlice.ts
frontend/tsconfig.json

Add infinite scroll and loading data with React Query

feat: #WB2-650, add skeleton and infinite loading and fixes

---

frontend/src/features/Actionbar/components/DeleteModal.tsx

Ticket : WB2-1022
- change variant on delete button : primary => danger

fix: #WB2-1022, fix change color delete button

---

frontend/index.html
frontend/src/app/root/index.tsx
frontend/src/features/Actionbar/components/EditResourceModal.tsx
frontend/src/services/queries/index.ts

Ticket : WB2-1025
Description : 
- Changement du component "Input" par un "TextArea" pour la description dans la modal de propriété.

feat: #WB2-1025, change component input by textarea

---

frontend/package.json
frontend/package.json.template
frontend/src/app/explorer/index.tsx
frontend/src/features/Explorer/components/SearchForm/SearchForm.tsx
frontend/vite.config.ts

Create component with search bar + filter in explorer module

feat(searchForm): #WB2-70 add SearchForm view

---

frontend/src/app/explorer/index.tsx
frontend/src/features/Actionbar/hooks/useEditResourceModal.tsx
frontend/src/features/Explorer/components/SearchForm/SearchForm.tsx
frontend/src/services/queries/index.ts
frontend/src/store/index.ts

Connect dropdown component to back-end

feat(dropdown): #WB2-69 connect dropdown to database

---

backend/src/test/java/com/opendigitaleducation/explorer/ResourceServiceTest.java

Mise à jour des tests unitaires suite à l'évolution : https://github.com/opendigitaleducation/entcore/pull/391

WB-2008 providing plain text content to explorer for indexation

---

frontend/src/features/Explorer/components/SearchForm/SearchForm.tsx
frontend/src/services/queries/index.ts
frontend/src/shared/utils/fullTextSearch.ts
frontend/src/store/index.ts

Ce commit branche le champs de recherche
La recherche est déclenché:
- automatiquement à partir de 3 caractères
- automatiquement si le champ de recherche est vide
- manuellement si le nombre de caractère est inférieur à 3 (clic sur la loupe ou touche "Enter")
- il y a un debounce 500ms
Les resources sont filtrés par le back (query params search)
Les dossiers sont filtrés par le front (car ils sont déjà tous retournés au front)

[EDIFICE] #Wb2-71 Integration du champs de recherche

---

frontend/index.html
frontend/src/features/ActionBar/useActionBar.tsx
frontend/src/services/api/index.ts
frontend/src/services/queries/index.ts
frontend/vite.config.ts

Add resource copy.
After selecting a resource, through the actionbar a user can now copy a resource.
https://edifice-community.atlassian.net/browse/WB2-850
>
>

feat: #WB2-850, add resource copy

---

frontend/src/services/queries/index.ts

Duplicate Backend API creates the duplicated resource in the root folder, so in case we are in another folder we need to move the duplicated resource to that folder.
>
>

fix: #WB2-1478, move duplicated resource to current folder after duplication

---

frontend/src/features/ActionBar/ActionBarContainer.tsx
frontend/src/features/ActionBar/Export/ExportModal.tsx
frontend/src/features/ActionBar/Export/useExportModal.ts
frontend/src/features/ActionBar/useActionBar.tsx

add Export Modal
https://edifice-community.atlassian.net/browse/WB2-1424
>
>

fix: #WB2-1424, add Export Modal

---

frontend/src/services/queries/index.ts

Use creation service returned thumbnail URL for new resource
>
>

fix: #WB2-1635, use creation service returned thumbnail URL for new resource

---

frontend/src/features/ActionBar/Folder/FolderModal.tsx

Add Folder Modal title maxLength
>
>

feat: #WB2-1496, add Folder Modal title maxLength

---

frontend/src/features/SideBar/Library/Library.tsx

Add Library promotion end of year
>
>

feat: #WB2-1689, add Library promotion end of year

---

frontend/src/features/SideBar/Library/Library.tsx

Get user language from session in Library component
>
>

fix: #WB2-1689, get user language from session in Library component

---

frontend/src/features/ActionBar/ActionBarContainer.tsx

See [PR](https://github.com/edificeio/edifice-ui/pull/187)
>
>
>

feat(ui): #WB2-1742, add shareOptions to make ShareModal compatible with any apps

---

backend/src/main/resources/scripts/.gitignore
backend/src/main/resources/scripts/clean/README.md
backend/src/main/resources/scripts/clean/build.sh
backend/src/main/resources/scripts/clean/index.js
backend/src/main/resources/scripts/clean/package.json

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Ce fix ajoute un script permettant de supprimer de l'index (et de la base Pg explorer) les documents qui n'existe plus dans la base de données primaire.
>
>

fix: #wb2-1804, clean documents from index

---

frontend/src/features/SideBar/Library/useLibrary.tsx

Put back previous Library image.
>
>

feat: #WB2-1777, set previous Library image

---

backend/src/main/java/com/opendigitaleducation/explorer/folders/FolderExplorerDbSql.java
backend/src/main/java/com/opendigitaleducation/explorer/services/impl/FolderServiceElastic.java

Ce fix permet de synchroniser les anciens dossiers parents lorsqu'on déplace un sous dossier (car le champ childrenIds ne se mettait pas à jour pour l'ancien parent...)
>
>
>

fix: #WB2-2099, sync old parent when moving folder
